vkOAuth(6031255, 'friends,groups',)
library("devtools")
library("plyr")
library("plyr")
library("mime")
library("curl")
library("R6")
library("openssl")
library("httr")
library("jsonlite")
library("XML")
library("vkR")
library("data.table")
#db_init()
wall <- getWallExecute(domain="data_mining_in_action", count=0, 
                       use_db=TRUE, db_params=list('collection'='dm', 'suffix'='posts'), progress_bar=TRUE)
show_collections()
friends <- getFriends()
users <- getUsersExecute(friends$items, use_db = TRUE, db_params=list('collection'='my_friends'), progress_bar = TRUE)
show_collections()
my_friends <- getFriends(fields = 'sex')
my_friends <- filter(my_friends$items, is.na(deactivated))